import React, { Component } from 'react';
import axios from 'axios';
import StockManagerList from './StockManagerList';

export default class AddStockManagerForm extends Component {

    state = {
        sname: '',
        semail: '',
        spassword: '',
        stel:'',

    }

    handleChange = event => {
        this.setState({
            [event.target.name]:event.target.value
        });
    }

    handleSubmit = event => {
        event.preventDefault();
        //make post request

        alert('Added Item to the System Successfully!')

        axios.post(`http://localhost:4000/stockManager`, this.state)
            .then(res => {
                console.log(res);
                console.log(res.data);
            })
    }

    render() {

        return (
            <div>
            <div className="container">
            <div className="row">

            <div className="col-md-4 order-md-2 mb-4">
            <StockManagerList />
            </div>

            <div className="col-md-8 order-md-1">
            <h4 className="mb-3"><b>Enter Stock Manager Details</b></h4>
        <form className="needs-validation" onSubmit={this.handleSubmit} noValidate>

        <div className="input-group mb-4">
            <div className="input-group-prepend">
            <span className="input-group-text" id="inputGroup-sizing-default">Product Code</span>
        </div>
        <input type="text" onChange={this.handleChange} className="form-control" placeholder="Generated by system" aria-label="Default" aria-describedby="inputGroup-sizing-default" disabled/>
        </div>

        <div className="input-group mb-4">
            <div className="input-group-prepend">
            <span className="input-group-text" id="inputGroup-sizing-default">Name</span>
        </div>
        <input type="text" name="sname" onChange={this.handleChange} className="form-control"  aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>
        </div>

        <div className="input-group mb-4">
            <div className="input-group-prepend">
            <span className="input-group-text" id="inputGroup-sizing-default">Email </span>
        </div>
        <input type="text" name="semail" onChange={this.handleChange} className="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>
        </div>

        <div className="input-group mb-4">
            <div className="input-group-prepend">
            <span className="input-group-text" id="inputGroup-sizing-default">Password</span>
            </div>
            <input type="text" name="spassword" onChange={this.handleChange} className="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>
        </div>

            <div className="input-group mb-4">
            <div className="input-group-prepend">
            <span className="input-group-text" id="inputGroup-sizing-default">Telephone</span>
            </div>
            <input type="textarea" name="stel" onChange={this.handleChange} className="form-control"  aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>
        </div>

        <hr className="mb-4" />

            <div className="row">
            <div className="col-md-6 mb-3">
            <button type="submit"  className="btn btn-primary btn-lg btn-block">Add StockManager</button>
        </div>
        <div className="col-md-6 mb-3">
            <a href="http://localhost:3000/"><button type="button" className="btn btn-danger btn-lg btn-block">Cancel</button></a>
        </div>
        </div>

        </form>
        </div>
        </div>
        </div>
        </div>
    )
    }
}