import React, { Component } from 'react';
import CategoryList from './CategoryList';

export default class AddItemForm extends Component {
    render() {
        return (
            <div>
                <div class="container">
                    <div class="row">

                        <div class="col-md-4 order-md-2 mb-4">
                            <CategoryList />
                        </div>
                        
                        <div class="col-md-8 order-md-1">
                            <h4 class="mb-3"><b>Enter Product Details</b></h4>
                            <form class="needs-validation" novalidate>
                                
                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default">Product Code</span>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Generated by system" aria-label="Default" aria-describedby="inputGroup-sizing-default" disabled/>
                                </div>

                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default">Product Name</span>
                                    </div>
                                    <input type="text" class="form-control"  aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>                                 
                                </div>

                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default">Product Price</span>
                                    </div>
                                    <input type="number" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>                                 
                                </div>

                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default">Quantity</span>
                                    </div>
                                    <input type="number" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" required/>                                 
                                </div>

                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="inputGroupSelect01">Category</label>
                                    </div>
                                    <select class="custom-select" id="inputGroupSelect01" required>
                                        <option selected>Choose Category</option>
                                        <option value="1">t-shirt</option>
                                    </select>
                                </div>

                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="inputGroupSelect01">Product Size</label>
                                    </div>
                                    <select class="custom-select" id="inputGroupSelect01">
                                        <option selected>Choose Size</option>
                                        <option value="XS">Extra Small</option>
                                        <option value="S">Small</option>
                                        <option value="M">Medium</option>
                                        <option value="L">Large</option>
                                        <option value="XL">Extra Large</option>
                                    </select>
                                </div>

                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="inputGroupSelect01">Age Range</label>
                                    </div>
                                    <select class="custom-select" id="inputGroupSelect01">
                                        <option selected>Choose Range</option>
                                        <option value="C">child</option>
                                        <option value="T">Teen</option>
                                        <option value="Y">Young</option>
                                        <option value="A">Adult</option>
                                    </select>
                                </div>

                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="inputGroupSelect01">Gender</label>
                                    </div>
                                    <select class="custom-select" id="inputGroupSelect01">
                                        <option selected>Choose Gender</option>
                                        <option value="M">Male</option>
                                        <option value="F">Female</option>
                                    </select>
                                </div>

                                

                                <hr class="mb-4" />

                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <button type="submit" class="btn btn-primary btn-lg btn-block">Add Product</button>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <button type="button" class="btn btn-danger btn-lg btn-block">Cancel</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}
